import { openai } from "./openAiClient";

export const generateBlogPost = async (prompt: string): Promise<string> => {
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4", // Make sure to use the right model
      messages: [
        {
          role: "system",
          content: "You are a helpful assistant that writes blog posts.",
        },
        {
          role: "user",
          content: prompt, // The user's prompt
        },
      ],
      max_tokens: 200, // Adjust the token count as needed
      temperature: 0.7, // Adjust for creativity
    });

    const content = response.choices[0].message?.content?.trim();
    if (!content) {
      throw new Error("No content generated by AI");
    }

    return content;
  } catch (error) {
    throw new Error(
      `Failed to generate blog post: ${(error as Error).message}`
    );
  }
};
