import "../globals.css";
import { Navigation } from "./_components/navigation/Navigation";

export const metadata = {
  title: "Auto Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
