import "../globals.css";
import { Navigation } from "./_components/navigation/Navigation";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Auto Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navigation />
          <>
            {children}
            <Toaster className="bg-background" />
          </>
        </body>
      </html>
    </ClerkProvider>
  );
}
