import "../globals.css";
import { Navigation } from "./_components/navigation/Navigation";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "./_components/themeProvider/themreProvider";

export const metadata = {
  title: "Auto Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navigation />
            <>
              {children}
              <Toaster />
            </>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
